### ISSUE TITLE
some papers missing

### ISSUE THREAD

**Issue by fawazsammani** [zhjohnchan/awesome-image-captioning#5]
Hi.....Thanks for this awesome page!
There are some papers in 2018 from ECCV which are not included. Perhaps you can add them.
- Exploring Visual Relationship for Image Captioning
- Boosted Attention: Leveraging Human Attention for Image Captioning
- Stylized Image Captioning with Adaptive Learning and Attention

 In Fact, the first one is the state-of-art. 

Regards

**Comment by zhjohnchan** [comment]
@fawazsammani Thank you very much, I have added them with your advice.
